<a href="https://colab.research.google.com/github/MathBSilva/Projeto-393/blob/main/Projeto01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import os

import numpy as np
from skimage import util, transform, filters, color, measure, morphology
from sklearn import model_selection, neighbors, metrics, preprocessing

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

%matplotlib notebook

# 3 classes - Conjunto completo
ds_path = '/content/drive/MyDrive/mpeg7_4classes_aug_x8_work/Test'

# Lista das pastas na pasta 'ds_path' (classes)
classes_list = os.listdir(ds_path)

# Lista com as imagens no dataset
image_list = []
# Lista com os rótulos das imagens
label_list = []

# Lista com os nomes das imagens
filename_list_ = []

# Percorre as classes do dataset
for classe in classes_list:
    
    # Listagem de todas as imagens na pasta daquela classe
    filename_list = os.listdir(os.path.join(ds_path, classe))
    
    # Percorre os arquivos na pasta atual
    for filename in filename_list:
        # Carrega a imagem
        img_temp = plt.imread(os.path.join(ds_path, classe, filename))
        
        # Redimensiona a imagem para 1/4 do tamanho original
        img_temp = transform.resize(img_temp, (img_temp.shape[0]//4, img_temp.shape[1]//4), anti_aliasing=True)
        
        # Adiciona a imagem a lista de imagens
        image_list.append(img_temp)
        
        # Adiciona o rótulo da imagem à lista de rótulos
        label_list.append(classe)
        
        # Adiciona o nome da imagem à uma lista (para fins de visualização)
        filename_list_.append(filename)

# Indices das classes dos objetos do dataset
_, _, label_list_idx = np.unique(label_list, return_index=True, return_inverse=True)

In [30]:
# Nomes das caracteristicas computadas
features = ['area', 'major_axis', 'minor_axis', 'solidity', 'eccentricity']

# Arranjo 2D com as caracteristicas das imagens
#   Cada linha armazena informações sobre uma imagem. Cada coluna armazena uma caracteristica.
#   [ [area, major_axis, minor_axis, solidity, eccentricity] ]
feature_mat = []

# Lista com as imagens segmentadas (binárias)
seg_list = []

# Lista com os rótulos das imagens
list_label = []

for i, (image, label) in enumerate(zip(image_list, label_list)):
    # DEBUG
    print('Imagem {} - classe {}'.format(i, label))
    
    # Adiciona o rótulos (label) da imagem à lista
    list_label.append(label)
    
    # Segmenta a imagem
    # --------------------------------------------------
    # Converte a imagem para float
    img_float = util.img_as_float(image)
    # DEBUG
    ## print(img_float.shape, img_float.min(), img_float.max())
    
    # Converte imagem para níveis de cinza
    img_float = color.rgb2gray(img_float)
    
    # Segmentação por limiarização usando Otsu
    img_seg = img_float < filters.threshold_otsu(img_float)
    # DEBUG
    ### print(img_seg.shape, img_seg.min(), img_seg.max())
    
    # Remove objetos na imagem com menos de N pixels.
    img_seg = morphology.remove_small_objects(img_seg, 10000)
    
    # Adiciona a imagem segmentada à lista.
    seg_list.append(img_seg)
    
    # Calcula a imagem de rótulos
    im_lbl = measure.label(img_seg)
    
    # Calcula uma lista de propriedades (caracteristicas) dos objetos na imagem
    props = measure.regionprops(im_lbl)
    
    ###print(len(props))
    if len(props) != 1:
        print(f'ERRO de segmentação: {len(props)}')
        continue

    # Itera pelas propriedades computadas
    for prop in props:
        # Prop. 0: Area
        area = prop.area
       
        # Prop. 1: Maior eixo
        major_axis = prop.major_axis_length
        
        # Prop. 2: Menor eixo
        minor_axis = prop.minor_axis_length 
        
        # Prop. 3: Solidez
        solidity = prop.solidity 
        
        # Prop. 4: Excentricidade
        eccentricity = prop.eccentricity 

        # Monta o vetor de caracteristicas deste objeto.
        feature_list = [area, major_axis, minor_axis, solidity, eccentricity]
    
    # Adiciona as caracteristicas desta imagem na matriz de caracteristicas
    feature_mat.append(feature_list)

Imagem 0 - classe apple
ERRO de segmentação: 0
Imagem 1 - classe apple
ERRO de segmentação: 0
Imagem 2 - classe apple
ERRO de segmentação: 0
Imagem 3 - classe apple
ERRO de segmentação: 0
Imagem 4 - classe apple
ERRO de segmentação: 0
Imagem 5 - classe apple
ERRO de segmentação: 0
Imagem 6 - classe apple
ERRO de segmentação: 0
Imagem 7 - classe apple
ERRO de segmentação: 0
Imagem 8 - classe apple
ERRO de segmentação: 0
Imagem 9 - classe apple
ERRO de segmentação: 0
Imagem 10 - classe apple
ERRO de segmentação: 0
Imagem 11 - classe apple
ERRO de segmentação: 0
Imagem 12 - classe apple
ERRO de segmentação: 0
Imagem 13 - classe apple
ERRO de segmentação: 0
Imagem 14 - classe apple
ERRO de segmentação: 0
Imagem 15 - classe apple
ERRO de segmentação: 0
Imagem 16 - classe apple
ERRO de segmentação: 0
Imagem 17 - classe apple
ERRO de segmentação: 0
Imagem 18 - classe apple
ERRO de segmentação: 0
Imagem 19 - classe apple
ERRO de segmentação: 0
Imagem 20 - classe apple
ERRO de segmentação: 0
Im

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:30: FutureWarning: The behavior of rgb2gray will change in scikit-image 0.19. Currently, rgb2gray allows 2D grayscale image to be passed as inputs and leaves them unmodified as outputs. Starting from version 0.19, 2D arrays will be treated as 1D images with 3 channels.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:30: FutureWarning: Non RGB image conversion is now deprecated. For RGBA images, please use rgb2gray(rgba2rgb(rgb)) instead. In version 0.19, a ValueError will be raised if input image last dimension length is not 3.


ERRO de segmentação: 0
Imagem 88 - classe beetle
ERRO de segmentação: 0
Imagem 89 - classe beetle
ERRO de segmentação: 0
Imagem 90 - classe beetle
ERRO de segmentação: 0
Imagem 91 - classe beetle
ERRO de segmentação: 0
Imagem 92 - classe beetle
Imagem 93 - classe beetle
Imagem 94 - classe beetle
ERRO de segmentação: 0
Imagem 95 - classe beetle
ERRO de segmentação: 0
Imagem 96 - classe beetle
ERRO de segmentação: 0
Imagem 97 - classe beetle
ERRO de segmentação: 0
Imagem 98 - classe beetle
ERRO de segmentação: 0
Imagem 99 - classe beetle
ERRO de segmentação: 0
Imagem 100 - classe beetle
ERRO de segmentação: 0
Imagem 101 - classe beetle
ERRO de segmentação: 0
Imagem 102 - classe beetle
ERRO de segmentação: 0
Imagem 103 - classe beetle
ERRO de segmentação: 0
Imagem 104 - classe beetle
ERRO de segmentação: 0
Imagem 105 - classe beetle
ERRO de segmentação: 0
Imagem 106 - classe beetle
ERRO de segmentação: 0
Imagem 107 - classe beetle
ERRO de segmentação: 0
Imagem 108 - classe bone
ERRO de se

In [31]:
# Converte a lista de caracteristicas para um arranjo NumPy
feature_map = np.array(feature_mat)

# Imprime a matriz de caracteristica
with np.printoptions(precision=4, suppress=True):
    print(feature_map)

[[21439.       201.5806   184.6808     0.8492     0.4008]
 [21439.       201.5806   184.6808     0.8492     0.4008]
 [21439.       201.5806   184.6808     0.8492     0.4008]
 [21439.       201.5806   184.6808     0.8492     0.4008]
 [20941.       194.6121   179.5983     0.8725     0.3852]
 [36713.       260.8268   246.5958     0.8489     0.3258]
 [33070.       236.5133   219.6467     0.9074     0.3709]
 [33070.       236.5133   219.6467     0.9074     0.3709]
 [20941.       194.6121   179.5983     0.8725     0.3852]
 [30626.       238.9234   217.3338     0.8629     0.4154]
 [26089.       222.9343   217.4451     0.8191     0.2205]
 [26089.       222.9343   217.4451     0.8191     0.2205]
 [12048.       156.0608   143.1558     0.8168     0.3982]
 [26089.       222.9343   217.4451     0.8191     0.2205]
 [30626.       238.9234   217.3338     0.8629     0.4154]
 [12048.       156.0608   143.1558     0.8168     0.3982]
 [30626.       238.9234   217.3338     0.8629     0.4154]
 [20941.      

In [32]:
# Seleciona apenas as primeiras N imagens de cada classe
seg_list_temp = []
filename_list_temp = []

# Itera pelo número de classes
for i in range(3):
    # As 6 primeiras ocorrencias em que label é igual a 'i'.
    seg_list_temp += [seg_list[j] for j in np.where(label_list_idx==i)[0][:6]]
    filename_list_temp += [filename_list_[j] for j in np.where(label_list_idx==i)[0][:6]]
fig, ax  = plt.subplots(3, 6, figsize=(9, 6))

for i, (image, filename) in enumerate(zip(seg_list_temp, filename_list_temp)):
    ax[i//6, i%6].imshow(image, cmap='gray')
    ax[i//6, i%6].set_title(str(filename))
    ax[i//6, i%6].axis('off')
    
fig.tight_layout()
plt.show()

<IPython.core.display.Javascript object>